development:
  adapter: mysql2
  host: localhost
  database: onyx
  username: root
  password: 1bigunicorn
  
test:
  adapter: mysql2
  host: localhost
  database: onyx
  username: root
  password: 1bigunicorn

production:
  adapter: mysql2
  host: localhost
  database: onyx
  username: root
  password: 1bigunicorn
